// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'articles': string;
  'layer': string;
}
export const cssExports: CssExports;
export default cssExports;
