// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'article-reactions': string;
  'avatar': string;
  'body': string;
  'commit-item': string;
  'commit-item-layer': string;
  'commit-layer': string;
  'head': string;
  'interact-layer': string;
  'join-columns': string;
  'reactions': string;
  'section': string;
  'unauth': string;
}
export const cssExports: CssExports;
export default cssExports;
