// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'article-loading-layer': string;
  'article-reactions': string;
  'boundary': string;
  'btns': string;
  'interact-layer': string;
  'join-columns': string;
  'reactions': string;
  'section': string;
  'unauth': string;
  'variable': string;
}
export const cssExports: CssExports;
export default cssExports;
