// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatar': string;
  'body': string;
  'commit-item': string;
  'commit-item-layer': string;
  'head': string;
  'unauth': string;
}
export const cssExports: CssExports;
export default cssExports;
