// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom': string;
  'indepen': string;
  'indepen-layer': string;
  'layer': string;
  'main': string;
  'right': string;
}
export const cssExports: CssExports;
export default cssExports;
