// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'bottom': string;
  'layer': string;
  'main': string;
  'right': string;
  'right-content': string;
  'right-layer': string;
}
export const cssExports: CssExports;
export default cssExports;
