// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'child-navs': string;
  'title': string;
  'top-navs': string;
}
export const cssExports: CssExports;
export default cssExports;
