// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'introduce': string;
  'navs': string;
  'portrait': string;
  'slide': string;
}
export const cssExports: CssExports;
export default cssExports;
