// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'place': string;
  'select-layer': string;
  'tip-layer': string;
  'warn': string;
}
export const cssExports: CssExports;
export default cssExports;
