// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'app1': string;
  'app2': string;
  'slide': string;
}
export const cssExports: CssExports;
export default cssExports;
