// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'avatar': string;
  'body': string;
  'btns': string;
  'chat': string;
  'commit-item': string;
  'commit-item-layer': string;
  'head': string;
  'input': string;
  'md-edit': string;
  'mode-tabs': string;
  'reactions': string;
}
export const cssExports: CssExports;
export default cssExports;
